USE [master]
GO

/****** Object:  Database [Klienci]    Script Date: 30.07.2020 09:02:36 ******/
CREATE DATABASE [Klienci]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Klienci', FILENAME = N'C:\Users\sebos\Klienci.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Klienci_log', FILENAME = N'C:\Users\sebos\Klienci_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Klienci].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Klienci] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Klienci] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Klienci] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Klienci] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Klienci] SET ARITHABORT OFF 
GO

ALTER DATABASE [Klienci] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Klienci] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Klienci] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Klienci] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Klienci] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Klienci] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Klienci] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Klienci] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Klienci] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Klienci] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Klienci] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Klienci] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Klienci] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Klienci] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Klienci] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Klienci] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Klienci] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Klienci] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Klienci] SET  MULTI_USER 
GO

ALTER DATABASE [Klienci] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Klienci] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Klienci] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Klienci] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Klienci] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Klienci] SET QUERY_STORE = OFF
GO

USE [Klienci]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Klienci] SET  READ_WRITE 
GO

